language: python
python:
  - "2.7"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/FullyFeatured-ESP8266 PLATFORMIO_CI_EXTRA_ARGS="--board=esp01 --board=nodemcuv2"
  - PLATFORMIO_CI_SRC=examples/FullyFeatured-ESP32 PLATFORMIO_CI_EXTRA_ARGS="--board=lolin32"
  - CPPLINT=true

install:
  - pip install -U https://github.com/platformio/platformio-core/archive/1b0776167c9dda9d5d30437a101ff0c6b138fafb.zip
  - pip install cpplint

script:
  - if [[ "$CPPLINT" ]]; then make cpplint; else platformio ci --lib=./ $PLATFORMIO_CI_EXTRA_ARGS; fi
